WebSaleCable/Areas/Administration/Controllers/ProductController.cs
using NuWebForSaler.Shared.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSaleCable.Shared;
using WebSaleCable.Shared.Factory.ProductFactory;
using WebSaleCable.Shared.Model.Product;
using WebSaleCable.Web.App_Start;

namespace WebSaleCable.Areas.Administration.Controllers
{
    [NuAuth]
    public class ProductController : BaseController
    {
        private ProductFactory _factory = null;
        // GET: Administration/Product
        public ProductController()
        {
            _factory = new ProductFactory();
        }
        // GET: Administration/House
        public ActionResult Index()
        {
            ProductViewModels model = new ProductViewModels();
            return View(model);
        }

        public ActionResult Search(ProductViewModels model)
        {
            try
            {
                var data = _factory.GetListProduct().ToList();
                data.ForEach(x =>
                {
                    if (!string.IsNullOrEmpty(x.ImageURL))
                        x.ImageURL = Commons.HostImage + x.ImageURL;
                });
                model.ListProduct = data;
            }
            catch (Exception e)
            {
                NSLog.Logger.Error("GetListHouse: ", e);
                return new HttpStatusCodeResult(400, e.Message);
            }
            return PartialView("_ListData", model);
        }

        [HttpGet]
        public PartialViewResult View(string id)
        {
            ProductModels model = GetDetail(id);
            return PartialView("_View", model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ProductModels model = new ProductModels();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(ProductModels model)
        {
            try
            {
                byte[] photoByte = null;
                if (model.PictureUpload != null && model.PictureUpload.ContentLength > 0)
                {
                    Byte[] imgByte = new Byte[model.PictureUpload.ContentLength];
                    model.PictureUpload.InputStream.Read(imgByte, 0, model.PictureUpload.ContentLength);
                    model.PictureByte = imgByte;
                    model.RawImageUrl = Guid.NewGuid() + Path.GetExtension(model.PictureUpload.FileName);
                    model.PictureUpload = null;
                    photoByte = imgByte;
                }

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if (!string.IsNullOrEmpty(model.RawImageUrl))
                {
                    model.ListImageUrl.Add(model.RawImageUrl);
                }
                //========
                Dictionary<int, byte[]> lstImgByte = new Dictionary<int, byte[]>();
                var ListImage = model.ListImg.Where(x => !x.IsDelete).ToList();
                foreach (var item in ListImage)
                {
                    if (item.PictureUpload != null && item.PictureUpload.ContentLength > 0)
                    {
                        Byte[] imgByte = new Byte[item.PictureUpload.ContentLength];
                        item.PictureUpload.InputStream.Read(imgByte, 0, item.PictureUpload.ContentLength);
                        item.PictureByte = imgByte;
                        item.ImageURL = Guid.NewGuid() + Path.GetExtension(item.PictureUpload.FileName);
                        item.PictureUpload = null;
                        lstImgByte.Add(item.OffSet, imgByte);
                        model.ListImageUrl.Add(item.ImageURL);
                    }
                }
                //====================
                string msg = "";
                bool result = _factory.InsertProduct(model, ref msg);
                if (result)
                {
                    if (!string.IsNullOrEmpty(model.RawImageUrl) && model.PictureByte != null)
                    {
                        var path = Server.MapPath("~/Uploads/Images/Product/" + model.RawImageUrl);
                        MemoryStream ms = new MemoryStream(photoByte, 0, photoByte.Length);
                        ms.Write(photoByte, 0, photoByte.Length);
                        System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);

                        ImageHelper.Me.SaveCroppedImageProduct(imageTmp, path, model.RawImageUrl, ref photoByte);
                    }

                    foreach (var item in ListImage)
                    {
                        if (!string.IsNullOrEmpty(item.ImageURL) && item.PictureByte != null)
                        {
                            var path = Server.MapPath("~/Uploads/Images/Product/" + item.ImageURL);
                            MemoryStream ms = new MemoryStream(lstImgByte[item.OffSet], 0, lstImgByte[item.OffSet].Length);
                            ms.Write(lstImgByte[item.OffSet], 0, lstImgByte[item.OffSet].Length);
                            System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);

                            ImageHelper.Me.SaveCroppedImageProduct(imageTmp, path, item.ImageURL, ref photoByte);
                        }
                    }
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("Name", msg);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                NSLog.Logger.Error("House_Create: ", ex);
                return new HttpStatusCodeResult(400, ex.Message);
            }
        }

        public ProductModels GetDetail(string id)
        {
            try
            {
                ProductModels model = _factory.GetDetailProduct(id);
                if (model != null)
                {
                    if (!string.IsNullOrEmpty(model.ImageURL))
                        model.ImageURL = Commons.HostImage + model.ImageURL;
                    if (model.ListImg != null && model.ListImg.Count > 0)
                    {
                        model.ListImg.ForEach(o => {
                            if (!string.IsNullOrEmpty(o.ImageURL))
                            {
                                o.ImageURL = Commons.HostImage + o.ImageURL;
                            }
                            o.IsDelete = false;
                        });
                    }
                    return model;
                }
                else
                {
                    model = new ProductModels();
                    return model;
                }
            }
            catch (Exception ex)
            {
                NSLog.Logger.Error("Product_Detail: ", ex);
                return null;
            }
        }

        public PartialViewResult Edit(string id)
        {
            ProductModels model = GetDetail(id);
            return PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(ProductModels model)
        {
            try
            {
                List<string> ListNotChangeImg = new List<string>();
                byte[] photoByte = null;

                if (!string.IsNullOrEmpty(model.ImageURL))
                {
                    model.ImageURL = model.ImageURL.Replace(Commons._PublicImages, "").Replace(Commons.Image200_100, "");
                    model.RawImageUrl = model.ImageURL;
                }
                if (model.PictureUpload != null && model.PictureUpload.ContentLength > 0)
                {
                    Byte[] imgByte = new Byte[model.PictureUpload.ContentLength];
                    model.PictureUpload.InputStream.Read(imgByte, 0, model.PictureUpload.ContentLength);
                    model.PictureByte = imgByte;
                    model.RawImageUrl = Guid.NewGuid() + Path.GetExtension(model.PictureUpload.FileName);
                    model.PictureUpload = null;
                    photoByte = imgByte;
                    if (!string.IsNullOrEmpty(model.ImageURL))
                    {
                        model.ImageURL = model.ImageURL.Replace(Commons._PublicImages, "").Replace(Commons.Image200_100, "");
                        ListNotChangeImg.Add(model.ImageURL);
                    }
                }

                if (!ModelState.IsValid)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return PartialView("_Edit", model);
                }
                if (!string.IsNullOrEmpty(model.RawImageUrl))
                {
                    model.ListImageUrl.Add(model.RawImageUrl);
                }

                //========
                Dictionary<int, byte[]> lstImgByte = new Dictionary<int, byte[]>();
                var ListImage = model.ListImg.Where(x => !x.IsDelete).ToList();
                foreach (var item in ListImage)
                {
                    if (item.PictureUpload != null && item.PictureUpload.ContentLength > 0)
                    {
                        if (!string.IsNullOrEmpty(item.ImageURL))
                        {
                            item.ImageURL = item.ImageURL.Replace(Commons._PublicImages, "").Replace(Commons.Image200_100, "");
                            ListNotChangeImg.Add(item.ImageURL);
                        }

                        Byte[] imgByte = new Byte[item.PictureUpload.ContentLength];
                        item.PictureUpload.InputStream.Read(imgByte, 0, item.PictureUpload.ContentLength);
                        item.PictureByte = imgByte;
                        item.ImageURL = Guid.NewGuid() + Path.GetExtension(item.PictureUpload.FileName);
                        item.PictureUpload = null;
                        lstImgByte.Add(item.OffSet, imgByte);

WebSaleCable/Areas/Administration/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSaleCable.Areas.Administration.Controllers
{
    public class ProfileController : HQController
    {
        // GET: Administration/Profile
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebSaleCable/Areas/Administration/Controllers/SliderController.cs
using NuWebForSaler.Shared.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using WebSaleCable.Shared;
using WebSaleCable.Shared.Model;
using WebSaleCable.Shared.Model.Product;

namespace WebSaleCable.Areas.Administration.Controllers
{
    public class SliderController : Controller
    {
        // GET: Administration/Slider
        public ActionResult Index()
        {
            var model = new SliderSession();
            try
            {
                var _Path = HostingEnvironment.MapPath("~/Images/silder/");
                var list = Directory.GetFiles(_Path).Select(x => Path.GetFileName(x)).ToList();
               
                if (list != null && list.Count > 0)
                {
                    for (var i = 0; i < list.Count; i++)
                    {
                        model.ListImg.Add(new ImageProduct
                        {
                            ImageURL = "~/Images/silder/" + list[i],
                            OffSet = i
                        });
                    }
                }
                else
                {
                    model.ListImg.Add(new ImageProduct
                    {
                        ImageURL = Commons.Image200_100,
                        OffSet = 0
                    });
                    model.ListImg.Add(new ImageProduct
                    {
                        ImageURL = Commons.Image200_100,
                        OffSet = 1
                    });
                    model.ListImg.Add(new ImageProduct
                    {
                        ImageURL = Commons.Image200_100,
                        OffSet = 2
                    });
                }
            }
            catch(Exception ex) {
                NSLog.Logger.Error("Index Slider : ", ex);
            }
            return View(model);
        }

        public ActionResult UpdateSlider(SliderSession model)
        {
            try
            {
                if(model.ListImg != null && model.ListImg.Any())
                {
                    foreach(var item in model.ListImg)
                    {
                        if (item.PictureUpload != null && item.PictureUpload.ContentLength > 0)
                        {
                            //Delete image 
                            if(System.IO.File.Exists(Server.MapPath(item.ImageURL)))
                            {
                                ImageHelper.Me.TryDeleteImageUpdated(Server.MapPath(item.ImageURL));
                            }
                            Byte[] imgByte = new Byte[item.PictureUpload.ContentLength];
                            item.PictureUpload.InputStream.Read(imgByte, 0, item.PictureUpload.ContentLength);
                            item.PictureByte = imgByte;
                            item.ImageURL = Guid.NewGuid() + Path.GetExtension(item.PictureUpload.FileName);
                            item.PictureUpload = null;

                            if (!string.IsNullOrEmpty(item.ImageURL) && item.PictureByte != null)
                            {
                                var path = Server.MapPath("~/Images/silder/" + item.ImageURL);
                                MemoryStream ms = new MemoryStream(imgByte, 0, imgByte.Length);
                                ms.Write(imgByte, 0, imgByte.Length);
                                System.Drawing.Image imageTmp = System.Drawing.Image.FromStream(ms, true);
                                byte[] photoByte = null;
                                ImageHelper.Me.SaveCroppedImageSilder(imageTmp, path, item.ImageURL, ref photoByte);
                            }
                        }
                    }
                }
            }catch(Exception ex)
            {
                NSLog.Logger.Error("UpdateSlider :", ex);
            }
            return RedirectToAction("Index");
        }
    }
}

WebSaleCable/Areas/Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @*<base href="@Url.Content("~/")"></base>*@
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Công ty Công Nghệ GB Việt Nam | @ViewBag.Title</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/bootstrap/dist/css/bootstrap.min.css")'>
    <!--Font Awesome-->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/font-awesome/css/font-awesome.min.css")'>

    <!--NProgress-->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/nprogress/nprogress.css")'>

    <!--iCheck-->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/iCheck/skins/flat/green.css")'>

    <!--bootstrap progressbar-->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css")'>

    <!--JQVMap-->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/jqvmap/dist/jqvmap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css")'>

    <!-- Switchery -->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/switchery/dist/switchery.min.css")'>

    <!-- Select2 -->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/select2/dist/css/select2.min.css")'>

    <!--Custom Theme Style-->
    <link rel="stylesheet" href='@Url.Content("~/Content/css/custom.min.css")'>

    <!-- Datatables -->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css")'>
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css")'>

    <!-- timepicker -->
    <link rel="stylesheet" href='@Url.Content("~/Libaraies/vendors/timepicker/bootstrap-timepicker.min.css")'>

    <link rel="stylesheet" href="@Url.Content("~/Libaraies/vendors/bootstrap-multiselect/bootstrap-multiselect.css")" type="text/css" />

    <!-- jQuery -->
    <script type="text/javascript" src="@Url.Content("~/Libaraies/vendors/jquery/dist/jquery.min.js")"></script>
    @*<link href="@Url.Content("~/Content/custom.scroll.css")" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">*@
    <script>
        var ROOT = '@Url.Content("~/")';
    </script>
    @RenderSection("Styles", false)
    <style>

     .cd-top {
  display: inline-block;
  height: 40px;
  width: 40px;
  position: fixed;
  bottom: 40px;
  right: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.05);
  /*font-family: 'Material Icons';*/
  /* image replacement properties */
  overflow: hidden;
  text-indent: 100%;
  white-space: nowrap;
  /*background: #d9534f url(../Assets/Images/cd-top-arrow.svg) no-repeat center 50%;*/
  visibility: hidden;
  opacity: 0;
  -webkit-transition: opacity .3s 0s, visibility 0s .3s;
  -moz-transition: opacity .3s 0s, visibility 0s .3s;
  transition: opacity .3s 0s, visibility 0s .3s;
  z-index:9999;
}
.cd-top.cd-is-visible, .cd-top.cd-fade-out, .no-touch .cd-top:hover {
  -webkit-transition: opacity .3s 0s, visibility 0s 0s;
  -moz-transition: opacity .3s 0s, visibility 0s 0s;
  transition: opacity .3s 0s, visibility 0s 0s;
}
.cd-top.cd-is-visible {
  /* the button becomes visible */
  visibility: visible;
  opacity: 1;
}
.cd-top.cd-fade-out {
  /* if the user keeps scrolling down, the button is out of focus and becomes less visible */
  opacity: .5;
}
.no-touch .cd-top:hover {
  background-color: #e86256;
  opacity: 1;
}
    </style>
</head>
<body class="nav-md footer_fixed">
    <a href="#0" class="cd-top">Top</a>
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0; background-color:#F2F2F2;">
                        <a href="@Url.Action("Index", "Home", new { area = "" })" class="site_title">
                            <span class="fa fa-home" style="color: black;">&nbsp; Công Nghệ GB </span>
                            @*<img src="~/Assets/Images/logo.png" height="35" />*@
                            
                        </a>
                    </div>
                    <div class="clearfix"></div>
                    @*<div class="profile">
                        @{
                            var user = Session["User"] as ProjectWebSaleLand.Shared.Models.UserSession;
                            if (user != null)
                            {
                                <div class="profile_pic">
                                    @if (user.ImageUrl == null)
                                    {
                                        <img src="@Url.Content("~/Assets/images/avatarDefault.jpg")" alt="..." class="img-circle profile_img" />
                                    }
                                    else
                                    {
                                        <img src="@user.ImageUrl" alt="..." class="img-circle profile_img">
                                    }
                                </div>
                                <div class="profile_info">
                                    <h2>@Html.Raw(user.UserName)</h2>
                                </div>
                            }
                        }
                    </div>*@
                    <br />
                    <!-- sidebar menu -->
                    @Html.Partial("_sidebarMenu")
                    <!-- /sidebar menu -->
                </div>
            </div>

            @Html.Partial("_topNavigation")
            @RenderBody()
            @*@Html.Partial("_footer")*@
        </div>
    </div>

    <!--Bootstrap-->
    <script src="@Url.Content("~/Libaraies/vendors/bootstrap/dist/js/bootstrap.min.js")"></script>
    <!--FastClick-->
    <script src="@Url.Content("~/Libaraies/vendors/fastclick/lib/fastclick.js")"></script>
    <!--NProgress-->
    <script src="@Url.Content("~/Libaraies/vendors/nprogress/nprogress.js")"></script>
    <!--bootstrap progressbar-->
    <script src="@Url.Content("~/Libaraies/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js")"></script>
    <!--iCheck-->
    <script src="@Url.Content("~/Libaraies/vendors/iCheck/icheck.min.js")"></script>
    <script src="@Url.Content("~/Scripts/js/custom.js")"></script>
    <!-- Switchery -->
    <script src="@Url.Content("~/Libaraies/vendors/switchery/dist/switchery.min.js")"></script>
    <!-- Validate -->
    <script src="@Url.Content("~/Scripts/js/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Scripts/js/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <!-- Custom Scroll bar -->

    <script src="@Url.Content("~/Libaraies/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js")"></script>

    <!-- Daterangepicker -->
    <script src="@Url.Content("~/Libaraies/vendors/moment/min/moment.min.js")"></script>
    <script src="@Url.Content("~/Libaraies/vendors/bootstrap-daterangepicker/daterangepicker.js")"></script>
    <!-- Select2  trongntn-->
    <script src="@Url.Content("~/Libaraies/vendors/select2/dist/js/select2.full.js")"></script>
    <!-- Datatables -->
    <script src="@Url.Content("~/Libaraies/vendors/datatables.net/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/Libaraies/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Libaraies/vendors/datatables.net-responsive/js/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/Libaraies/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js")"></script>
    <script src="@Url.Content("~/Libaraies/vendors/datatables.net-scroller/js/datatables.scroller.min.js")"></script>
    <script src="@Url.Content("~/Libaraies/vendors/timepicker/bootstrap-timepicker.min.js")"></script>

    
    <script src="@Url.Content("~/Scripts/js/validator.js")"></script>
    <script src="@Url.Content("~/Scripts/js/jcommon.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Libaraies/vendors/bootstrap-multiselect/bootstrap-multiselect.js")"></script>

    <script type="text/javascript">
            @{
                string controller = this.ViewContext.RouteData.Values["controller"].ToString();
                string baseUrl = new Uri(Request.Url, Url.Content("~")).ToString();
            }
        ControllerName = "@controller";
        BaseUrl = "@baseUrl";
        $(document).ready(function () {
            $(".timepicker").timepicker({
                timeFormat: 'HH:mm',
                showInputs: false,
                showMeridian: false
            });
        });
        $(function () {
            // browser window scroll (in pixels) after which the "back to top" link is shown
            var offset = 300,
                //browser window scroll (in pixels) after which the "back to top" link opacity is reduced
                offset_opacity = 1200,
                //duration of the top scrolling animation (in ms)
                scroll_top_duration = 350,
                //grab the "back to top" link
                $back_to_top = $('.cd-top');

            //hide or show the "back to top" link
            $(window).scroll(function () {
                ($(this).scrollTop() > offset) ? $back_to_top.addClass('cd-is-visible') : $back_to_top.removeClass('cd-is-visible cd-fade-out');
                if ($(this).scrollTop() > offset_opacity) {
                    $back_to_top.addClass('cd-fade-out');
                }
            });

            //smooth scroll to top
            $back_to_top.on('click', function (event) {
                event.preventDefault();
                $('body,html').animate({
                    scrollTop: 0,
                }, scroll_top_duration
                );
            });

        });
    </script>

    @*<script src="@Url.Content("~/Scripts/functions.js")"></script>*@
    @RenderSection("Scripts", false)



</body>
</html>

WebSaleCable/Areas/Administration/Views/Shared/_breadcrumb.cshtml
<h4>@Model["A"] <small> <i class="fa fa-angle-double-right"></i> <span style="font-size:16px;">@Model["B"]</span> <i class="fa fa-angle-double-right"></i> @Model["C"] </small></h4>

WebSaleCable/Areas/Administration/Views/Shared/_footer.cshtml
<br />
<br />
<footer>
   
    @*<div class="pull-left">
        Version: <strong>@ViewBag.Version</strong>
    </div>*@

    <div class="pull-right">
        <strong>&copy; @DateTime.Now.Year.ToString() <a href="#" target="_blank">Công ty Cổ Phần Sản Xuất Và Phát Triển Công Nghệ GB Việt Nam</a></strong>
    </div>
    <div class="clearfix"></div>
</footer>

WebSaleCable/Areas/Administration/Views/Shared/_popupConfirmation.cshtml
<div id="modal_@Model[0]" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title" id="myModalLabel2" style="text-align: left">@Model[1]</h4>
            </div>
            <div class="modal-body">
                <p>@Model[2]</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="delete (@Model[3])">Đồng ý </button>
            </div>
        </div>
    </div>
</div>

WebSaleCable/Areas/Administration/Views/Shared/_sidebarMenu.cshtml
@*@using ProjectWebSaleLand.Web.App_Start;*@
@{
    var user = Session["User"] as WebSaleCable.Shared.Models.UserSession;
}

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>&nbsp;</h3>
        <ul class="nav side-menu">
            <li id="">
                <a><i class="fa fa-cogs"></i>Quản lý<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu"> 
                    <li><a href="@Url.Action("Index", "Location", new { area = "Administration" })">Khu vực</a></li> 
                    <li><a href="@Url.Action("Index", "Category", new { area = "Administration" })">Thể loại</a></li> 
                    <li><a href="@Url.Action("Index", "Product", new { area = "Administration" })">Sản phẩm</a></li>  
                    <li><a href="@Url.Action("Index", "Employee", new { area = "Administration" })">Nhân viên</a></li>
                    <li><a href="@Url.Action("Index", "Customer", new { area = "Administration" })">Khách hàng</a></li>
                </ul>
            </li>  
            <li id="">
                <a><i class="fa fa-image"></i>Hình ảnh<span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="@Url.Action("Index", "Slider", new { area = "Administration" })">Slider</a></li>
                </ul>
            </li>  
        </ul>
    </div>
</div>
<script>
    $(document).ready(function () {
        
    });
</script>

WebSaleCable/Areas/Administration/Views/Shared/_topNavigation.cshtml
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        @*<img src="@Url.Content("~/Assets/images/picture.jpg")" alt="" />*@
                        @{
                            var user = Session["User"] as WebSaleCable.Shared.Models.UserSession;
                            if (user != null)
                            {
                                if (user.ImageUrl == null || user.ImageUrl.Length == 0) {
                                    <img src="@Url.Content("~/Assets/images/avatarDefault.jpg")" alt="" />
                                    }
                                    else
                                    {
                                        <img src = "@user.ImageUrl" alt = "" />
                                    }
                                    @Html.Raw(user.UserName)
                            }

                            }
                        <span class="fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        @*<li><a href="@Url.Action("Index","Profile", new { area = "" })"> Profile</a></li>*@
                        <li><a href="@Url.Action("Logout", "Home", new { area = "Administration" })"><i class="fa fa-sign-out pull-right"></i>Đăng xuất</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>